#!/usr/bin/zsh

# takes two dates (anything that date(1) can accept. best: YYYY-MM-DD) and returns the number of days between them. If no $2, then assumes today
#

first=$1
second=$2
[ -z $first ] && echo "I need a date!" && exit 1
[ -z $second ] && second=$(date +%Y-%m-%d)

sectot=$(( $(date -d $second +%s) - $(date -d $first +%s) ))

echo "$(showtime -s $sectot)"
# this should be in an echo triggered by a verbose flag?
# ($sectot seconds)"
