#!/bin/bash

# the original idea was condensed down to these few lines... before being expanded again to handle a date(1) compatible offset in $1
#
#d=$(date "+%a %b %d %T %Y %Z")
bon=$(tput rev)
boff=$(tput sgr0)
#
#zdump US/Hawaii US/Alaska US/Pacific US/Mountain US/Central US/Eastern Pacific/Easter Brazil/East UTC Europe/London Europe/Rome Africa/Cairo Asia/Baghdad Europe/Moscow Asia/Calcutta Asia/Bangkok Asia/Hong_Kong Australia/West Asia/Tokyo Australia/North Australia/Brisbane Australia/South Australia/NSW Pacific/Fiji Pacific/Auckland | sed -e "s/  /,/g ; s/, /,/g ; s/$d/$bon$d$boff/g" | column -t -s,


when=${1:-now}
abswhen=$(date -Iseconds -d "$when")
z=$(date -d "$when" "+%z")

# TODO: 
# indicate timezone name as well. 
# debian: text string in /etc/timezone
# centos/rh: binary contents of /etc/localtime (might be symlink sometimes?)
#

# version 2 used this loop (with better output), but failed on absolute strings.
# so now it's used to calculate the local (reference) timezone name
TZNAMEtmp=$( (for t in US/Hawaii US/Alaska US/Pacific US/Mountain US/Central US/Eastern Pacific/Easter Brazil/East UTC Europe/London Europe/Rome Africa/Cairo Asia/Baghdad Europe/Moscow Asia/Calcutta Asia/Bangkok Asia/Hong_Kong Australia/West Asia/Tokyo Australia/North Australia/South Australia/Brisbane Australia/NSW Pacific/Fiji Pacific/Auckland ; do
    echo "$t,$(TZ=$t date -d "$when" "+%z")"
done) | grep -m 1 $z | cut -d, -f 1 )

# if our attempt to calculate a TZ name fails, we have a default
TZNAME=${TZNAMEtmp:-UTC}

# version 3: pretty much the V2 loop, but with the TZ=TZNAME param. 
# ...we now handle both absolute and relative time

(for t in US/Hawaii US/Alaska US/Pacific US/Mountain US/Central US/Eastern Pacific/Easter Brazil/East UTC Europe/London Europe/Rome Africa/Cairo Asia/Baghdad Europe/Moscow Asia/Calcutta Asia/Bangkok Asia/Hong_Kong Australia/West Asia/Tokyo Australia/North Australia/South Australia/Brisbane Australia/NSW Pacific/Fiji Pacific/Auckland ; do
    echo "$t,$(TZ=$t date -d "TZ=\"$TZNAME\" $abswhen" "+%z, %a %b %d %T %Y %Z$boff")"
done) | sed -e "s/$z/$bon$z/g" | column -t -s,
